/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`create_rate_limit`]
#[derive(Clone, Debug)]
pub struct CreateRateLimitParams {
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    pub service_sid: String,
    /// Provides a unique and addressable name to be assigned to this Rate Limit, assigned by the developer, to be optionally used in addition to SID. **This value should not contain PII.**
    pub unique_name: String,
    /// Description of this Rate Limit
    pub description: Option<String>
}

/// struct for passing parameters to the method [`delete_rate_limit`]
#[derive(Clone, Debug)]
pub struct DeleteRateLimitParams {
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    pub service_sid: String,
    /// The Twilio-provided string that uniquely identifies the Rate Limit resource to fetch.
    pub sid: String
}

/// struct for passing parameters to the method [`fetch_rate_limit`]
#[derive(Clone, Debug)]
pub struct FetchRateLimitParams {
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    pub service_sid: String,
    /// The Twilio-provided string that uniquely identifies the Rate Limit resource to fetch.
    pub sid: String
}

/// struct for passing parameters to the method [`list_rate_limit`]
#[derive(Clone, Debug)]
pub struct ListRateLimitParams {
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    pub service_sid: String,
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<i64>,
    /// The page index. This value is simply for client state.
    pub page: Option<i32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>
}

/// struct for passing parameters to the method [`update_rate_limit`]
#[derive(Clone, Debug)]
pub struct UpdateRateLimitParams {
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    pub service_sid: String,
    /// The Twilio-provided string that uniquely identifies the Rate Limit resource to fetch.
    pub sid: String,
    /// Description of this Rate Limit
    pub description: Option<String>
}


/// struct for typed errors of method [`create_rate_limit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRateLimitError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_rate_limit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRateLimitError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_rate_limit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchRateLimitError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_rate_limit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRateLimitError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_rate_limit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateRateLimitError {
    UnknownValue(serde_json::Value),
}


/// Create a new Rate Limit for a Service
pub async fn create_rate_limit(configuration: &configuration::Configuration, params: CreateRateLimitParams) -> Result<models::VerifyV2ServiceRateLimit, Error<CreateRateLimitError>> {

    let uri_str = format!("{}/v2/Services/{ServiceSid}/RateLimits", configuration.base_path, ServiceSid=crate::apis::urlencode(params.service_sid));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("UniqueName", params.unique_name.to_string());
    if let Some(param_value) = params.description {
        multipart_form_params.insert("Description", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateRateLimitError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a specific Rate Limit.
pub async fn delete_rate_limit(configuration: &configuration::Configuration, params: DeleteRateLimitParams) -> Result<(), Error<DeleteRateLimitError>> {

    let uri_str = format!("{}/v2/Services/{ServiceSid}/RateLimits/{Sid}", configuration.base_path, ServiceSid=crate::apis::urlencode(params.service_sid), Sid=crate::apis::urlencode(params.sid));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteRateLimitError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch a specific Rate Limit.
pub async fn fetch_rate_limit(configuration: &configuration::Configuration, params: FetchRateLimitParams) -> Result<models::VerifyV2ServiceRateLimit, Error<FetchRateLimitError>> {

    let uri_str = format!("{}/v2/Services/{ServiceSid}/RateLimits/{Sid}", configuration.base_path, ServiceSid=crate::apis::urlencode(params.service_sid), Sid=crate::apis::urlencode(params.sid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchRateLimitError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve a list of all Rate Limits for a service.
pub async fn list_rate_limit(configuration: &configuration::Configuration, params: ListRateLimitParams) -> Result<models::ListRateLimitResponse, Error<ListRateLimitError>> {

    let uri_str = format!("{}/v2/Services/{ServiceSid}/RateLimits", configuration.base_path, ServiceSid=crate::apis::urlencode(params.service_sid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListRateLimitResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListRateLimitResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListRateLimitError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a specific Rate Limit.
pub async fn update_rate_limit(configuration: &configuration::Configuration, params: UpdateRateLimitParams) -> Result<models::VerifyV2ServiceRateLimit, Error<UpdateRateLimitError>> {

    let uri_str = format!("{}/v2/Services/{ServiceSid}/RateLimits/{Sid}", configuration.base_path, ServiceSid=crate::apis::urlencode(params.service_sid), Sid=crate::apis::urlencode(params.sid));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = params.description {
        multipart_form_params.insert("Description", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VerifyV2ServiceRateLimit`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateRateLimitError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

