/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccessTokenEnumFactorTypes : The Type of the Factor. Currently only `push` is supported.
/// The Type of the Factor. Currently only `push` is supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessTokenEnumFactorTypes {
    #[serde(rename = "push")]
    Push,

}

impl std::fmt::Display for AccessTokenEnumFactorTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Push => write!(f, "push"),
        }
    }
}

impl Default for AccessTokenEnumFactorTypes {
    fn default() -> AccessTokenEnumFactorTypes {
        Self::Push
    }
}

