/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FormEnumFormTypes : The Type of this Form. Currently only `form-push` is supported.
/// The Type of this Form. Currently only `form-push` is supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormEnumFormTypes {
    #[serde(rename = "form-push")]
    FormPush,

}

impl std::fmt::Display for FormEnumFormTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FormPush => write!(f, "form-push"),
        }
    }
}

impl Default for FormEnumFormTypes {
    fn default() -> FormEnumFormTypes {
        Self::FormPush
    }
}

