/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListMessagingConfigurationResponse {
    #[serde(rename = "messaging_configurations", skip_serializing_if = "Option::is_none")]
    pub messaging_configurations: Option<Vec<models::VerifyV2ServiceMessagingConfiguration>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListBucketResponseMeta>>,
}

impl ListMessagingConfigurationResponse {
    pub fn new() -> ListMessagingConfigurationResponse {
        ListMessagingConfigurationResponse {
            messaging_configurations: None,
            meta: None,
        }
    }
}

