/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRateLimitResponse {
    #[serde(rename = "rate_limits", skip_serializing_if = "Option::is_none")]
    pub rate_limits: Option<Vec<models::VerifyV2ServiceRateLimit>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListBucketResponseMeta>>,
}

impl ListRateLimitResponse {
    pub fn new() -> ListRateLimitResponse {
        ListRateLimitResponse {
            rate_limits: None,
            meta: None,
        }
    }
}

