/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVerificationAttemptResponse {
    #[serde(rename = "attempts", skip_serializing_if = "Option::is_none")]
    pub attempts: Option<Vec<models::VerifyV2VerificationAttempt>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListBucketResponseMeta>>,
}

impl ListVerificationAttemptResponse {
    pub fn new() -> ListVerificationAttemptResponse {
        ListVerificationAttemptResponse {
            attempts: None,
            meta: None,
        }
    }
}

