/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListChallengeResponse {
    #[serde(rename = "challenges", skip_serializing_if = "Option::is_none")]
    pub challenges: Option<Vec<models::VerifyV2ServiceEntityChallenge>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListBucketResponseMeta>>,
}

impl ListChallengeResponse {
    pub fn new() -> ListChallengeResponse {
        ListChallengeResponse {
            challenges: None,
            meta: None,
        }
    }
}

