/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewFactorEnumNotificationPlatforms {
    #[serde(rename = "apn")]
    Apn,
    #[serde(rename = "fcm")]
    Fcm,
    #[serde(rename = "none")]
    None,

}

impl std::fmt::Display for NewFactorEnumNotificationPlatforms {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Apn => write!(f, "apn"),
            Self::Fcm => write!(f, "fcm"),
            Self::None => write!(f, "none"),
        }
    }
}

impl Default for NewFactorEnumNotificationPlatforms {
    fn default() -> NewFactorEnumNotificationPlatforms {
        Self::Apn
    }
}

