/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewFactorEnumFactorTypes : The Type of this Factor. Currently `push` and `totp` are supported.
/// The Type of this Factor. Currently `push` and `totp` are supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewFactorEnumFactorTypes {
    #[serde(rename = "push")]
    Push,
    #[serde(rename = "totp")]
    Totp,
    #[serde(rename = "passkeys")]
    Passkeys,

}

impl std::fmt::Display for NewFactorEnumFactorTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Push => write!(f, "push"),
            Self::Totp => write!(f, "totp"),
            Self::Passkeys => write!(f, "passkeys"),
        }
    }
}

impl Default for NewFactorEnumFactorTypes {
    fn default() -> NewFactorEnumFactorTypes {
        Self::Push
    }
}

