/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewFactorEnumFactorStatuses : The Status of this Factor. One of `unverified` or `verified`.
/// The Status of this Factor. One of `unverified` or `verified`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewFactorEnumFactorStatuses {
    #[serde(rename = "unverified")]
    Unverified,
    #[serde(rename = "verified")]
    Verified,

}

impl std::fmt::Display for NewFactorEnumFactorStatuses {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unverified => write!(f, "unverified"),
            Self::Verified => write!(f, "verified"),
        }
    }
}

impl Default for NewFactorEnumFactorStatuses {
    fn default() -> NewFactorEnumFactorStatuses {
        Self::Unverified
    }
}

