/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationAttemptsSummaryEnumChannels {
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "whatsapp")]
    Whatsapp,
    #[serde(rename = "rbm")]
    Rbm,

}

impl std::fmt::Display for VerificationAttemptsSummaryEnumChannels {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sms => write!(f, "sms"),
            Self::Call => write!(f, "call"),
            Self::Email => write!(f, "email"),
            Self::Whatsapp => write!(f, "whatsapp"),
            Self::Rbm => write!(f, "rbm"),
        }
    }
}

impl Default for VerificationAttemptsSummaryEnumChannels {
    fn default() -> VerificationAttemptsSummaryEnumChannels {
        Self::Sms
    }
}

