/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2ServiceVerification {
    /// The unique string that we created to identify the Verification resource.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    #[serde(rename = "service_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification resource.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The phone number or [email](https://www.twilio.com/docs/verify/email) being verified. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<String>>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<models::VerificationEnumChannel>,
    /// The status of the verification. Can be: `pending`, `approved`, `canceled`, `max_attempts_reached`, `deleted`, `failed` or `expired`.
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// Use \"status\" instead. Legacy property indicating whether the verification was successful.
    #[serde(rename = "valid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub valid: Option<Option<bool>>,
    /// Information about the phone number being verified.
    #[serde(rename = "lookup", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lookup: Option<Option<serde_json::Value>>,
    /// The amount of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<String>>,
    /// The payee of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled.
    #[serde(rename = "payee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payee: Option<Option<String>>,
    /// An array of verification attempt objects containing the channel attempted and the channel-specific transaction SID.
    #[serde(rename = "send_code_attempts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub send_code_attempts: Option<Option<Vec<serde_json::Value>>>,
    /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The set of fields used for a silent network auth (`sna`) verification. Contains a single field with the URL to be invoked to verify the phone number.
    #[serde(rename = "sna", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sna: Option<Option<serde_json::Value>>,
    /// The absolute URL of the Verification resource.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl VerifyV2ServiceVerification {
    pub fn new() -> VerifyV2ServiceVerification {
        VerifyV2ServiceVerification {
            sid: None,
            service_sid: None,
            account_sid: None,
            to: None,
            channel: None,
            status: None,
            valid: None,
            lookup: None,
            amount: None,
            payee: None,
            send_code_attempts: None,
            date_created: None,
            date_updated: None,
            sna: None,
            url: None,
        }
    }
}

