/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2Service {
    /// The unique string that we created to identify the Service resource.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The name that appears in the body of your verification messages. It can be up to 30 characters long and can include letters, numbers, spaces, dashes, underscores. Phone numbers, special characters or links are NOT allowed. It cannot contain more than 4 (consecutive or non-consecutive) digits. **This value should not contain PII.**
    #[serde(rename = "friendly_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<Option<String>>,
    /// The length of the verification code to generate.
    #[serde(rename = "code_length", skip_serializing_if = "Option::is_none")]
    pub code_length: Option<i32>,
    /// Whether to perform a lookup with each verification started and return info about the phone number.
    #[serde(rename = "lookup_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lookup_enabled: Option<Option<bool>>,
    /// Whether to pass PSD2 transaction parameters when starting a verification.
    #[serde(rename = "psd2_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub psd2_enabled: Option<Option<bool>>,
    /// Whether to skip sending SMS verifications to landlines. Requires `lookup_enabled`.
    #[serde(rename = "skip_sms_to_landlines", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub skip_sms_to_landlines: Option<Option<bool>>,
    /// Whether to ask the user to press a number before delivering the verify code in a phone call.
    #[serde(rename = "dtmf_input_required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dtmf_input_required: Option<Option<bool>>,
    /// The name of an alternative text-to-speech service to use in phone calls. Applies only to TTS languages.
    #[serde(rename = "tts_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tts_name: Option<Option<String>>,
    /// Whether to add a security warning at the end of an SMS verification body. Disabled by default and applies only to SMS. Example SMS body: `Your AppName verification code is: 1234. Don’t share this code with anyone; our employees will never ask for the code`
    #[serde(rename = "do_not_share_warning_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub do_not_share_warning_enabled: Option<Option<bool>>,
    /// Whether to allow sending verifications with a custom code instead of a randomly generated one.
    #[serde(rename = "custom_code_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_code_enabled: Option<Option<bool>>,
    /// Configurations for the Push factors (channel) created under this Service.
    #[serde(rename = "push", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub push: Option<Option<serde_json::Value>>,
    /// Configurations for the TOTP factors (channel) created under this Service.
    #[serde(rename = "totp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub totp: Option<Option<serde_json::Value>>,
    #[serde(rename = "default_template_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_template_sid: Option<Option<String>>,
    #[serde(rename = "whatsapp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub whatsapp: Option<Option<serde_json::Value>>,
    #[serde(rename = "passkeys", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub passkeys: Option<Option<serde_json::Value>>,
    /// Whether to allow verifications from the service to reach the stream-events sinks if configured
    #[serde(rename = "verify_event_subscription_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verify_event_subscription_enabled: Option<Option<bool>>,
    /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The absolute URL of the resource.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    /// The URLs of related resources.
    #[serde(rename = "links", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub links: Option<Option<serde_json::Value>>,
}

impl VerifyV2Service {
    pub fn new() -> VerifyV2Service {
        VerifyV2Service {
            sid: None,
            account_sid: None,
            friendly_name: None,
            code_length: None,
            lookup_enabled: None,
            psd2_enabled: None,
            skip_sms_to_landlines: None,
            dtmf_input_required: None,
            tts_name: None,
            do_not_share_warning_enabled: None,
            custom_code_enabled: None,
            push: None,
            totp: None,
            default_template_sid: None,
            whatsapp: None,
            passkeys: None,
            verify_event_subscription_enabled: None,
            date_created: None,
            date_updated: None,
            url: None,
            links: None,
        }
    }
}

