/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2VerificationTemplate {
    /// A 34 character string that uniquely identifies a Verification Template.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The unique SID identifier of the Account.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// A descriptive string that you create to describe a Template. It can be up to 32 characters long.
    #[serde(rename = "friendly_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<Option<String>>,
    /// A list of channels that support the Template. Can include: sms, voice.
    #[serde(rename = "channels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Option<Vec<String>>>,
    /// An object that contains the different translations of the template. Every translation is identified by the language short name and contains its respective information as the approval status, text and created/modified date.
    #[serde(rename = "translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub translations: Option<Option<serde_json::Value>>,
}

impl VerifyV2VerificationTemplate {
    pub fn new() -> VerifyV2VerificationTemplate {
        VerifyV2VerificationTemplate {
            sid: None,
            account_sid: None,
            friendly_name: None,
            channels: None,
            translations: None,
        }
    }
}

