/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerificationEnumStatus : The status of the verification. Can be: `pending`, `approved`, `canceled`, `max_attempts_reached`, `deleted`, `failed` or `expired`.
/// The status of the verification. Can be: `pending`, `approved`, `canceled`, `max_attempts_reached`, `deleted`, `failed` or `expired`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationEnumStatus {
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "approved")]
    Approved,

}

impl std::fmt::Display for VerificationEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Canceled => write!(f, "canceled"),
            Self::Approved => write!(f, "approved"),
        }
    }
}

impl Default for VerificationEnumStatus {
    fn default() -> VerificationEnumStatus {
        Self::Canceled
    }
}

