/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2ServiceVerificationCheck {
    /// The unique string that we created to identify the VerificationCheck resource.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    #[serde(rename = "service_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the VerificationCheck resource.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The phone number or [email](https://www.twilio.com/docs/verify/email) being verified. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<String>>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<models::VerificationCheckEnumChannel>,
    /// The status of the verification. Can be: `pending`, `approved`, `canceled`, `max_attempts_reached`, `deleted`, `failed` or `expired`.
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// Use \"status\" instead. Legacy property indicating whether the verification was successful.
    #[serde(rename = "valid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub valid: Option<Option<bool>>,
    /// The amount of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<String>>,
    /// The payee of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled.
    #[serde(rename = "payee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payee: Option<Option<String>>,
    /// The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the Verification Check resource was created.
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time in GMT when the Verification Check resource was last updated.
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// List of error codes as a result of attempting a verification using the `sna` channel. The error codes are chronologically ordered, from the first attempt to the latest attempt. This will be an empty list if no errors occured or `null` if the last channel used wasn't `sna`.
    #[serde(rename = "sna_attempts_error_codes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sna_attempts_error_codes: Option<Option<Vec<serde_json::Value>>>,
}

impl VerifyV2ServiceVerificationCheck {
    pub fn new() -> VerifyV2ServiceVerificationCheck {
        VerifyV2ServiceVerificationCheck {
            sid: None,
            service_sid: None,
            account_sid: None,
            to: None,
            channel: None,
            status: None,
            valid: None,
            amount: None,
            payee: None,
            date_created: None,
            date_updated: None,
            sna_attempts_error_codes: None,
        }
    }
}

