/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2Form {
    #[serde(rename = "form_type", skip_serializing_if = "Option::is_none")]
    pub form_type: Option<models::FormEnumFormTypes>,
    /// Object that contains the available forms for this type. This available forms are given in the standard [JSON Schema](https://json-schema.org/) format
    #[serde(rename = "forms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub forms: Option<Option<serde_json::Value>>,
    /// Additional information for the available forms for this type. E.g. The separator string used for `binding` in a Factor push.
    #[serde(rename = "form_meta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub form_meta: Option<Option<serde_json::Value>>,
    /// The URL to access the forms for this type.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl VerifyV2Form {
    pub fn new() -> VerifyV2Form {
        VerifyV2Form {
            form_type: None,
            forms: None,
            form_meta: None,
            url: None,
        }
    }
}

