/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationAttemptEnumAttemptStatus {
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
    #[serde(rename = "expired")]
    Expired,

}

impl std::fmt::Display for VerificationAttemptEnumAttemptStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Confirmed => write!(f, "confirmed"),
            Self::Unconfirmed => write!(f, "unconfirmed"),
            Self::Expired => write!(f, "expired"),
        }
    }
}

impl Default for VerificationAttemptEnumAttemptStatus {
    fn default() -> VerificationAttemptEnumAttemptStatus {
        Self::Confirmed
    }
}

