/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerificationCheckEnumChannel : The verification method to use. One of: [`email`](https://www.twilio.com/docs/verify/email), `sms`, `whatsapp`, `call`, or `sna`.
/// The verification method to use. One of: [`email`](https://www.twilio.com/docs/verify/email), `sms`, `whatsapp`, `call`, or `sna`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationCheckEnumChannel {
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "whatsapp")]
    Whatsapp,
    #[serde(rename = "sna")]
    Sna,

}

impl std::fmt::Display for VerificationCheckEnumChannel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sms => write!(f, "sms"),
            Self::Call => write!(f, "call"),
            Self::Email => write!(f, "email"),
            Self::Whatsapp => write!(f, "whatsapp"),
            Self::Sna => write!(f, "sna"),
        }
    }
}

impl Default for VerificationCheckEnumChannel {
    fn default() -> VerificationCheckEnumChannel {
        Self::Sms
    }
}

