/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2ServiceRateLimitBucket {
    /// A 34 character string that uniquely identifies this Bucket.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The Twilio-provided string that uniquely identifies the Rate Limit resource.
    #[serde(rename = "rate_limit_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rate_limit_sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
    #[serde(rename = "service_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit resource.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// Maximum number of requests permitted in during the interval.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i32>,
    /// Number of seconds that the rate limit will be enforced over.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i32>,
    /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The URL of this resource.
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl VerifyV2ServiceRateLimitBucket {
    pub fn new() -> VerifyV2ServiceRateLimitBucket {
        VerifyV2ServiceRateLimitBucket {
            sid: None,
            rate_limit_sid: None,
            service_sid: None,
            account_sid: None,
            max: None,
            interval: None,
            date_created: None,
            date_updated: None,
            url: None,
        }
    }
}

