/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2VerificationAttempt {
    /// The SID that uniquely identifies the verification attempt resource.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification resource.
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) used to generate the attempt.
    #[serde(rename = "service_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<Option<String>>,
    /// The SID of the [Verification](https://www.twilio.com/docs/verify/api/verification) that generated the attempt.
    #[serde(rename = "verification_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_sid: Option<Option<String>>,
    /// The date that this Attempt was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The date that this Attempt was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    #[serde(rename = "conversion_status", skip_serializing_if = "Option::is_none")]
    pub conversion_status: Option<models::VerificationAttemptEnumConversionStatus>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<models::VerificationAttemptEnumChannels>,
    /// An object containing the charge for this verification attempt related to the channel costs and the currency used. The costs related to the succeeded verifications are not included. May not be immediately available. More information on pricing is available [here](https://www.twilio.com/en-us/verify/pricing).
    #[serde(rename = "price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price: Option<Option<serde_json::Value>>,
    /// An object containing the channel specific information for an attempt.
    #[serde(rename = "channel_data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_data: Option<Option<serde_json::Value>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl VerifyV2VerificationAttempt {
    pub fn new() -> VerifyV2VerificationAttempt {
        VerifyV2VerificationAttempt {
            sid: None,
            account_sid: None,
            service_sid: None,
            verification_sid: None,
            date_created: None,
            date_updated: None,
            conversion_status: None,
            channel: None,
            price: None,
            channel_data: None,
            url: None,
        }
    }
}

