/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyV2VerificationAttemptsSummary {
    /// Total of attempts made according to the provided filters
    #[serde(rename = "total_attempts", skip_serializing_if = "Option::is_none")]
    pub total_attempts: Option<i32>,
    /// Total of  attempts made that were confirmed by the end user, according to the provided filters.
    #[serde(rename = "total_converted", skip_serializing_if = "Option::is_none")]
    pub total_converted: Option<i32>,
    /// Total of attempts made that were not confirmed by the end user, according to the provided filters.
    #[serde(rename = "total_unconverted", skip_serializing_if = "Option::is_none")]
    pub total_unconverted: Option<i32>,
    /// Percentage of the confirmed messages over the total, defined by (total_converted/total_attempts)*100. 
    #[serde(rename = "conversion_rate_percentage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub conversion_rate_percentage: Option<Option<String>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl VerifyV2VerificationAttemptsSummary {
    pub fn new() -> VerifyV2VerificationAttemptsSummary {
        VerifyV2VerificationAttemptsSummary {
            total_attempts: None,
            total_converted: None,
            total_unconverted: None,
            conversion_rate_percentage: None,
            url: None,
        }
    }
}

