/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerificationAttemptEnumConversionStatus : A string specifying the conversion status of the verification. A conversion happens when the user is able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`.
/// A string specifying the conversion status of the verification. A conversion happens when the user is able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationAttemptEnumConversionStatus {
    #[serde(rename = "converted")]
    Converted,
    #[serde(rename = "unconverted")]
    Unconverted,

}

impl std::fmt::Display for VerificationAttemptEnumConversionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Converted => write!(f, "converted"),
            Self::Unconverted => write!(f, "unconverted"),
        }
    }
}

impl Default for VerificationAttemptEnumConversionStatus {
    fn default() -> VerificationAttemptEnumConversionStatus {
        Self::Converted
    }
}

