/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookEnumVersion : The webhook version. Default value is `v2` which includes all the latest fields. Version `v1` is legacy and may be removed in the future.
/// The webhook version. Default value is `v2` which includes all the latest fields. Version `v1` is legacy and may be removed in the future.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookEnumVersion {
    #[serde(rename = "v1")]
    V1,
    #[serde(rename = "v2")]
    V2,

}

impl std::fmt::Display for WebhookEnumVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::V1 => write!(f, "v1"),
            Self::V2 => write!(f, "v2"),
        }
    }
}

impl Default for WebhookEnumVersion {
    fn default() -> WebhookEnumVersion {
        Self::V1
    }
}

