/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookEnumMethods : The method to be used when calling the webhook's URL.
/// The method to be used when calling the webhook's URL.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookEnumMethods {
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,

}

impl std::fmt::Display for WebhookEnumMethods {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Get => write!(f, "GET"),
            Self::Post => write!(f, "POST"),
        }
    }
}

impl Default for WebhookEnumMethods {
    fn default() -> WebhookEnumMethods {
        Self::Get
    }
}

